### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by johannesjo** [ireade/formhack#12]
I know this is super old. But could you @ireade possibly add a MIT licence anyway? I like the approach and would like to hack this for my project, but without a proper licence I cannot use it in my employers commercial project.

**Comment by ireade** [comment]
Done! Thanks for using the project :)

https://github.com/ireade/formhack/blob/master/LICENSE.md

**Comment by johannesjo** [comment]
Wonderful! Thank you very much!
