### ISSUE TITLE
LESS

### ISSUE THREAD

**Issue by reubeningber** [ireade/formhack#3]
Would you be interested in having someone port this to LESS?

**Comment by ireade** [comment]
That would be great!

**Comment by reubeningber** [comment]
Cool I will work on it over the weekend proably.

**Comment by ireade** [comment]
Awesome, thanks

**Comment by thejspro** [comment]
Where can I find the LESS port of this library?

**Comment by ireade** [comment]
Hi @goodpixels! Unfortunately it doesn't exist right now, and I don't use LESS
